apiVersion: v1
kind: Namespace
metadata:
  name: backend-team
  labels:
    team: chainsaw-coders
    cost-center: backend
    department: engineering
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: team-info
  namespace: backend-team
data:
  team-name: "The Chainsaw Coders"
  mission: "Own the backend systems for logistics, stock management, and supplier integrations"
  cost-center: "backend"
  department: "engineering"
  budget: "60000"
  lead: "mark.backend@woodsystems.io"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logistics-api
  namespace: backend-team
  labels:
    app: logistics-api
    team: chainsaw-coders
spec:
  replicas: 4
  selector:
    matchLabels:
      app: logistics-api
  template:
    metadata:
      labels:
        app: logistics-api
        team: chainsaw-coders
    spec:
      containers:
        - name: api
          image: ghcr.io/stefanprodan/podinfo:6.5.4
          ports:
            - containerPort: 9898
          env:
            - name: PODINFO_UI_COLOR
              value: "#C62828"
            - name: PODINFO_UI_MESSAGE
              value: "Logistics API"
          resources:
            requests:
              cpu: 300m
              memory: 512Mi
            limits:
              cpu: 600m
              memory: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-management
  namespace: backend-team
  labels:
    app: stock-management
    team: chainsaw-coders
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stock-management
  template:
    metadata:
      labels:
        app: stock-management
        team: chainsaw-coders
    spec:
      containers:
        - name: api
          image: ghcr.io/stefanprodan/podinfo:6.5.4
          ports:
            - containerPort: 9898
          env:
            - name: PODINFO_UI_COLOR
              value: "#6A1B9A"
            - name: PODINFO_UI_MESSAGE
              value: "Stock Management"
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supplier-integration
  namespace: backend-team
  labels:
    app: supplier-integration
    team: chainsaw-coders
spec:
  replicas: 2
  selector:
    matchLabels:
      app: supplier-integration
  template:
    metadata:
      labels:
        app: supplier-integration
        team: chainsaw-coders
    spec:
      containers:
        - name: integration
          image: kennethreitz/httpbin:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 200m
              memory: 384Mi
            limits:
              cpu: 400m
              memory: 768Mi
---
apiVersion: v1
kind: Service
metadata:
  name: logistics-api
  namespace: backend-team
spec:
  selector:
    app: logistics-api
  ports:
    - port: 9898
      targetPort: 9898
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: stock-management
  namespace: backend-team
spec:
  selector:
    app: stock-management
  ports:
    - port: 9898
      targetPort: 9898
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: supplier-integration
  namespace: backend-team
spec:
  selector:
    app: supplier-integration
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
