apiVersion: v1
kind: Namespace
metadata:
  name: ai-team
  labels:
    team: tree-mendous-ai
    cost-center: data-ai
    department: engineering
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: team-info
  namespace: ai-team
data:
  team-name: "Tree-mendous AI"
  mission: "Build AI and data analytics tools for forest management, inventory prediction, and pricing optimization"
  cost-center: "data-ai"
  department: "engineering"
  budget: "75000"
  lead: "sarah.analytics@woodsystems.io"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-inference
  namespace: ai-team
  labels:
    app: ml-inference
    team: tree-mendous-ai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ml-inference
  template:
    metadata:
      labels:
        app: ml-inference
        team: tree-mendous-ai
    spec:
      containers:
        - name: ml-service
          image: ghcr.io/stefanprodan/podinfo:6.5.4
          ports:
            - containerPort: 9898
          env:
            - name: PODINFO_UI_COLOR
              value: "#1976D2"
            - name: PODINFO_UI_MESSAGE
              value: "Tree-mendous AI - ML Inference"
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 4Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-processing
  namespace: ai-team
  labels:
    app: data-processing
    team: tree-mendous-ai
spec:
  replicas: 3
  selector:
    matchLabels:
      app: data-processing
  template:
    metadata:
      labels:
        app: data-processing
        team: tree-mendous-ai
    spec:
      containers:
        - name: worker
          image: polinux/stress-ng:latest
          command: ["stress-ng"]
          args:
            - --cpu
            - "2"
            - --cpu-load
            - "60"
            - --timeout
            - "0"
          resources:
            requests:
              cpu: 400m
              memory: 512Mi
            limits:
              cpu: 800m
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: ml-inference
  namespace: ai-team
spec:
  selector:
    app: ml-inference
  ports:
    - port: 9898
      targetPort: 9898
  type: ClusterIP
