apiVersion: apps/v1
kind: Deployment
metadata:
  name: opencost
spec:
  template:
    spec:
      containers:
        - name: opencost
          env:
            # Azure Managed Prometheus configuration
            - name: PROMETHEUS_SERVER_ENDPOINT
              value: "https://defaultazuremonitorworkspace-neu-gwh8g8e2g3bxh7d6.northeurope.prometheus.monitor.azure.com"
