apiVersion: v1
kind: ServiceMonitor
metadata:
  name: opencost
  namespace: opencost
  labels:
    app: opencost
spec:
  selector:
    matchLabels:
      app: opencost
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
