apiVersion: v1
kind: Namespace
metadata:
  name: frontend
  labels:
    app: frontend
    team: web
    cost-center: engineering
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: frontend
  labels:
    app: podinfo
    team: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
        team: web
    spec:
      containers:
        - name: podinfo
          image: ghcr.io/stefanprodan/podinfo:6.5.4
          ports:
            - containerPort: 9898
              name: http
              protocol: TCP
            - containerPort: 9797
              name: http-metrics
              protocol: TCP
            - containerPort: 9999
              name: grpc
              protocol: TCP
          command:
            - ./podinfo
            - --port=9898
            - --grpc-port=9999
            - --grpc-service-name=podinfo
            - --level=info
          env:
            - name: PODINFO_UI_COLOR
              value: "#34577c"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9898
          readinessProbe:
            httpGet:
              path: /readyz
              port: 9898
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: podinfo
  namespace: frontend
spec:
  selector:
    app: podinfo
  ports:
    - port: 9898
      targetPort: 9898
      name: http
    - port: 9999
      targetPort: 9999
      name: grpc
  type: ClusterIP
