apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
  - cluster-issuer-letsencrypt-staging.yaml
  - cluster-issuer-letsencrypt-prod.yaml

commonLabels:
  app.kubernetes.io/managed-by: argocd
