apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-tracking
  namespace: login-team
  labels:
    app: order-tracking
    team: login
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-tracking
  template:
    metadata:
      labels:
        app: order-tracking
        team: login
    spec:
      containers:
        - name: podinfo
          image: ghcr.io/stefanprodan/podinfo:6.5.4
          ports:
            - containerPort: 9898
          env:
            - name: PODINFO_UI_COLOR
              value: "#388E3C"
            - name: PODINFO_UI_MESSAGE
              value: "Order Tracking Service"
          resources:
            requests:
              cpu: 150m
              memory: 192Mi
            limits:
              cpu: 300m
              memory: 384Mi
---
apiVersion: v1
kind: Service
metadata:
  name: order-tracking
  namespace: login-team
spec:
  selector:
    app: order-tracking
  ports:
    - port: 9898
      targetPort: 9898
  type: ClusterIP
