apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: base-ingress
  namespace: argocd
  labels:
    kcdporto: components
  annotations:
    argocd.argoproj.io/sync-wave: "1" # Deploy after cert-manager (wave 0)
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:infbase/kcdporto2025
    targetRevision: main
    path: components/ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m