apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: argocd
  labels:
    kcdporto: components
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/headlamp/
    targetRevision: 0.36.0 # Latest stable version
    chart: headlamp
    helm:
      values: |
        service:
          type: ClusterIP
        config:
          pluginsDir: "/headlamp/plugins"
        initContainers:
          - name: install-plugins
            image: node:20-alpine
            command:
              - /bin/sh
              - -c
              - |
                npm install -g @headlamp-k8s/plugin-manager
                mkdir -p /headlamp/plugins
                cd /headlamp/plugins
                npx @headlamp-k8s/plugin-manager install @headlamp-k8s/plugin-cert-manager
                npx @headlamp-k8s/plugin-manager install @headlamp-k8s/plugin-opencost
            volumeMounts:
              - name: plugins
                mountPath: /headlamp/plugins
        volumeMounts:
          - name: plugins
            mountPath: /headlamp/plugins
        volumes:
          - name: plugins
            emptyDir: {}
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: headlamp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
