apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: argocd
  labels:
    kcdporto: components
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/headlamp/
    targetRevision: 0.36.0 # Latest stable version
    chart: headlamp
    helm:
      values: |
        service:
          type: ClusterIP
        config:
          pluginsDir: "/headlamp/plugins"
          watchPlugins: true
          inCluster: true
        pluginsManager:
          enabled: true
          securityContext:
            readOnlyRootFilesystem: false
            runAsNonRoot: false
            runAsUser: 0
          configContent: |
            plugins:
              - name: cert-manager
                source: https://artifacthub.io/packages/headlamp/headlamp-plugins/headlamp_cert-manager
                version: 0.1.0
              - name: opencost
                source: https://artifacthub.io/packages/headlamp/headlamp-plugins/headlamp_opencost
                version: 0.1.3
            installOptions:
              parallel: true
              maxConcurrent: 2
          baseImage: node:lts-alpine
          version: latest
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: headlamp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
