apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kyverno.github.io/kyverno/
    targetRevision: 3.5.2
    chart: kyverno
    helm:
      values: |
        # Enable background processing for policy reports
        backgroundController:
          enabled: true

        # Enable cleanup controller
        cleanupController:
          enabled: true

        # Enable reports controller
        reportsController:
          enabled: true

        # Configure admission controller
        admissionController:
          replicas: 3
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
