apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opencost
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://opencost.github.io/opencost-helm-chart
    targetRevision: 1.40.0
    chart: opencost
    helm:
      values: |
        clusterName: kcdporto-aks

        opencost:
          prometheus:
            internal:
              enabled: false
            external:
              enabled: true
              url: https://defaultazuremonitorworkspace-neu-gwh8g8e2g3bxh7d6.northeurope.prometheus.monitor.azure.com
              bearerTokenFile: /var/run/secrets/tokens/azure-identity-token
          exporter:
            extraEnv:
              AZURE_USE_WORKLOAD_IDENTITY_AUTH: "true"

        # Enable workload identity
        podAnnotations:
          azure.workload.identity/use: "true"

        serviceAccount:
          annotations:
            azure.workload.identity/client-id: "8e91df16-1b7e-46b3-a5ed-7acc4fee28c8"

        # Mount Azure identity token for authentication
        extraVolumeMounts:
          - name: azure-identity-token
            mountPath: /var/run/secrets/tokens
            readOnly: true

        extraVolumes:
          - name: azure-identity-token
            projected:
              defaultMode: 420
              sources:
                - serviceAccountToken:
                    audience: api://AzureADTokenExchange
                    expirationSeconds: 3600
                    path: azure-identity-token
  destination:
    server: https://kubernetes.default.svc
    namespace: opencost
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
