apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 25.30.1
    chart: prometheus
    helm:
      values: |
        server:
          remoteWrite:
            - url: https://defaultazuremonitorworkspace-neu-gwh8g8e2g3bxh7d6.northeurope.prometheus.monitor.azure.com/prometheus/api/v1/write
              oauth2:
                client_id: "f3231852-1c04-4c18-8a96-478d82b82251"
                client_secret_file: "/etc/prometheus/secrets/azure-prometheus-credentials/client-secret"
                token_url: "https://login.microsoftonline.com/0c568ebc-c62f-4671-8c99-51ad25cb084c/oauth2/v2.0/token"
                scopes:
                  - "https://monitor.azure.com/.default"
          extraSecretMounts:
            - name: azure-prometheus-credentials
              mountPath: /etc/prometheus/secrets/azure-prometheus-credentials
              secretName: azure-prometheus-credentials
              readOnly: true
          retention: 2d
          persistentVolume:
            enabled: true
            size: 8Gi
          service:
            type: ClusterIP

        alertmanager:
          enabled: false

        nodeExporter:
          enabled: true

        kubeStateMetrics:
          enabled: true

        pushgateway:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
