apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: components
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 25.30.1
    chart: prometheus
    helm:
      values: |
        server:
          retention: 15d
          persistentVolume:
            enabled: true
            size: 8Gi
          service:
            type: ClusterIP

        alertmanager:
          enabled: false

        nodeExporter:
          enabled: true

        kubeStateMetrics:
          enabled: true

        pushgateway:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
