apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-resource-limits
  annotations:
    policies.kyverno.io/title: Require Resource Limits
    policies.kyverno.io/category: FinOps Best Practices
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Requires all containers to have CPU and memory limits defined.
      This is crucial for cost predictability and prevents resource
      overuse that can lead to unexpected cloud bills.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: require-cpu-limits
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "CPU limits are required for all containers"
        pattern:
          spec:
            containers:
              - resources:
                  limits:
                    cpu: "?*"
    - name: require-memory-limits
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Memory limits are required for all containers"
        pattern:
          spec:
            containers:
              - resources:
                  limits:
                    memory: "?*"
    - name: require-requests
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Resource requests are required for proper scheduling and cost allocation"
        pattern:
          spec:
            containers:
              - resources:
                  requests:
                    memory: "?*"
                    cpu: "?*"
